name: leaflet_map_app1
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_map: 
  latlong2: 
  geolocator: ^10.1.0
  font_awesome_flutter: ^9.2.0
  gap: ^3.0.1
  get: ^4.0.0
  osrm:
  flutter_typeahead: ^4.0.0
  location_picker_flutter_map: 
  geocoding: ^2.1.0
  validation_textformfield: ^2.2.5
  location: ^5.0.3
  nominatim_flutter: ^0.0.2
  routing_client_dart: ^0.5.2
  url_launcher: ^6.1.11
  http: ^1.1.0
  google_sign_in: ^5.2.1
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0 
  flutter_facebook_auth: ^6.0.3
  flutter_screenutil: ^5.9.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  another_flushbar: ^1.12.30
  more_loading_gif: ^0.0.3
  flutter_dotenv: ^5.1.0
  rename: ^3.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    # uncomment the below loens 
    - secure/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
